import React, { useState, useRef } from 'react';
import { 
  X, Plus, FileText, Sparkles, ClipboardCopy, 
  Download, ChevronLeft, Info, Check, 
  Trash2, Edit3, MessageSquare, List,
  CheckCircle2, Loader2, ArrowRight,
  HelpCircle, MoreVertical, Layout,
  Settings, Database, GraduationCap,
  History, Eye, Save, Wand2, FileSearch,
  BookOpen, AlignLeft, Home, FileOutput,
  Upload, Terminal, RefreshCw, Hash,
  ChevronRight, Copy
} from 'lucide-react';
import { generateQuizFromPDF, reconstructQuizFromUnstructured } from '../services/geminiService';
import { FormattedResponse } from './AIModal';

interface Question {
  id: string;
  type: 'multiple-choice' | 'true-false' | 'short-answer';
  text: string;
  options?: string[];
  answer?: string;
  explanation?: string;
}

interface QuizStudioProps {
  onClose: () => void;
  onConvertToDoc?: (title: string, content: string) => void;
  isTeacher?: boolean;
}

const QuizStudio: React.FC<QuizStudioProps> = ({ onClose, onConvertToDoc, isTeacher = false }) => {
  const [view, setView] = useState<'hub' | 'editor' | 'importer'>('hub');
  const [isGenerating, setIsGenerating] = useState(false);
  const [quizTitle, setQuizTitle] = useState('Untitled Quiz');
  const [questions, setQuestions] = useState<Question[]>([]);
  
  // Importer state
  const [reconstructedOutput, setReconstructedOutput] = useState<string | null>(null);
  const [importText, setImportText] = useState('');
  const [importFile, setImportFile] = useState<{ name: string; base64: string } | null>(null);
  
  // Generation Config
  const [prompt, setPrompt] = useState('');
  const [selectedTypes, setSelectedTypes] = useState<string[]>(['multiple-choice']);
  const [includeExplanations, setIncludeExplanations] = useState(true);
  const [questionCount, setQuestionCount] = useState(10);

  const fileInputRef = useRef<HTMLInputElement>(null);

  const toggleType = (type: string) => {
    setSelectedTypes(prev => 
      prev.includes(type) ? prev.filter(t => t !== type) : [...prev, type]
    );
  };

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    setIsGenerating(true);
    
    try {
      const systemPrompt = `
        ACT AS AN EDUCATIONAL ARCHITECT. Generate a quiz based on: "${prompt}".
        RULES:
        1. Generate exactly ${questionCount} questions.
        2. Format: Use **QUESTION [N]** for headers.
        3. Options: Use A), B), C), D) for choices.
        4. Answers: Wrap the key in ==Answer==.
        5. MANDATORY: Provide a section **WHY THIS IS CORRECT** explaining the pedagogical reasoning for every answer.
        6. Valid Types: ${selectedTypes.join(', ')}.
        7. PROVIDE OUTPUT IN CLEAN HUMAN READABLE PLAIN TEXT. NO HASHES (#).
      `;

      const result = await generateQuizFromPDF(btoa(systemPrompt)); 
      
      setQuestions([{ 
        id: 'gen-' + Math.random().toString(36).substr(2, 5), 
        type: 'multiple-choice', 
        text: result.text,
        explanation: 'Generated by Tehila intelligence node.'
      }]);
      
      setView('editor');
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleImportFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = () => {
        const result = reader.result as string;
        const base64 = result.includes(',') ? result.split(',')[1] : result;
        setImportFile({ name: file.name, base64 });
      };
      reader.readAsDataURL(file);
    }
  };

  const handleRunImport = async () => {
    if (!importText.trim() && !importFile) return;
    setIsGenerating(true);
    try {
      const result = await reconstructQuizFromUnstructured(
        importFile ? importFile.base64 : importText,
        !!importFile
      );
      setReconstructedOutput(result.text);
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const commitToEditor = () => {
    if (!reconstructedOutput) return;
    setQuestions([{
      id: 'import-' + Math.random().toString(36).substr(2, 5),
      type: 'multiple-choice',
      text: reconstructedOutput
    }]);
    setReconstructedOutput(null);
    setView('editor');
  };

  const handleExportToDoc = () => {
    if (!onConvertToDoc) return;
    const fullContent = questions.map(q => q.text).join('\n\n---\n\n');
    onConvertToDoc(quizTitle, fullContent);
  };

  const renderHub = () => (
    <div className="flex-1 flex flex-col items-center justify-center p-12 bg-white animate-in fade-in duration-500">
      <div className="flex flex-col items-center mb-16">
        <h2 className="text-2xl font-black text-[#002D56] uppercase tracking-widest mb-2">Quiz Intelligence Hub</h2>
        <p className="text-slate-400 text-sm font-medium">Cognitive Suite Node Active</p>
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 max-w-7xl w-full">
        <button 
          onClick={() => { setView('editor'); setQuestions([]); }}
          className="bg-white border border-slate-200 rounded-2xl p-10 flex flex-col items-center text-center group hover:border-[#135bec] hover:shadow-2xl transition-all duration-500 h-full"
        >
          <div className="w-20 h-24 border-2 border-[#135bec] rounded-lg flex items-center justify-center mb-10 relative overflow-hidden group-hover:bg-blue-50/50 transition-colors">
            <Plus size={32} className="text-[#135bec]" />
          </div>
          <h3 className="text-xl font-black text-[#002D56] mb-4">Blank Quiz</h3>
          <p className="text-sm text-slate-400 font-medium leading-relaxed">Jump right in and build something great from scratch.</p>
        </button>

        <button 
          onClick={() => setView('editor')}
          className="bg-white border border-slate-200 rounded-2xl p-10 flex flex-col items-center text-center group hover:border-[#135bec] hover:shadow-2xl transition-all duration-500 h-full"
        >
          <div className="w-20 h-24 border-2 border-[#135bec] rounded-lg flex flex-col p-4 mb-10 relative overflow-hidden group-hover:bg-blue-50/50 transition-colors">
            <div className="h-1 w-full bg-slate-200 rounded-full mb-2" />
            <div className="h-1 w-3/4 bg-slate-200 rounded-full mb-2" />
            <div className="h-1 w-full bg-slate-200 rounded-full" />
            <div className="absolute bottom-4 right-4">
               <Sparkles size={24} className="text-orange-400 fill-orange-400" />
            </div>
          </div>
          <div className="flex items-center gap-3 mb-4">
             <h3 className="text-xl font-black text-[#002D56]">Generate</h3>
             <span className="px-2 py-0.5 bg-emerald-50 text-emerald-600 rounded text-[9px] font-black uppercase tracking-widest border border-emerald-100">BETA</span>
          </div>
          <p className="text-sm text-slate-400 font-medium leading-relaxed">Describe your quiz and AI will create your first draft.</p>
        </button>

        <button 
          onClick={() => { setView('importer'); setReconstructedOutput(null); }}
          className="bg-white border border-slate-200 rounded-2xl p-10 flex flex-col items-center text-center group hover:border-[#135bec] hover:shadow-2xl transition-all duration-500 h-full"
        >
          <div className="w-20 h-24 border-2 border-[#135bec] rounded-lg flex items-center justify-center mb-10 group-hover:bg-blue-50/50 transition-colors">
            <Download className="text-[#135bec]" size={32} />
          </div>
          <h3 className="text-xl font-black text-[#002D56] mb-4">Import Asset</h3>
          <p className="text-sm text-slate-400 font-medium leading-relaxed">Import a quiz from messy text, old PDFs, or images.</p>
        </button>

        <button 
          onClick={() => { setView('importer'); setReconstructedOutput(null); }}
          className="bg-white border border-slate-200 rounded-2xl p-10 flex flex-col items-center text-center group hover:border-[#135bec] hover:shadow-2xl transition-all duration-500 h-full"
        >
          <div className="w-20 h-24 flex items-center justify-center mb-10 relative group-hover:scale-105 transition-transform">
             <div className="absolute top-0 right-0 w-14 h-16 border-2 border-[#135bec] rounded-lg bg-white" />
             <div className="absolute bottom-0 left-0 w-14 h-16 border-2 border-[#135bec] rounded-lg bg-white flex items-center justify-center">
                <ArrowRight className="rotate-45 text-[#135bec]" size={24} strokeWidth={3} />
             </div>
          </div>
          <div className="flex items-center gap-3 mb-4">
             <h3 className="text-xl font-black text-[#002D56]">Quick Paste</h3>
             <span className="px-2 py-0.5 bg-emerald-50 text-emerald-600 rounded text-[9px] font-black uppercase tracking-widest border border-emerald-100">BETA</span>
          </div>
          <p className="text-sm text-slate-400 font-medium leading-relaxed">Paste questions from another resource and convert them instantly.</p>
        </button>
      </div>
    </div>
  );

  const renderImporter = () => (
    <div className="flex-1 flex overflow-hidden bg-white animate-in slide-in-from-right-4 duration-500">
       <div className="flex-1 flex flex-col overflow-y-auto custom-scrollbar border-r border-slate-100 bg-slate-50/30">
          <div className="p-12 max-w-4xl mx-auto w-full">
             <nav className="flex items-center gap-2 text-sm font-medium mb-12">
                <button onClick={() => setView('hub')} className="text-blue-600 hover:underline flex items-center gap-1">
                  <ChevronLeft size={16} /> Hub
                </button>
                <span className="text-slate-300">/</span>
                <span className="text-slate-900 font-bold uppercase tracking-widest text-xs">Import Studio</span>
             </nav>

             <div className="space-y-8">
                <div className="bg-white rounded-[3rem] p-12 shadow-2xl border border-slate-100 relative">
                   <div className="flex items-center justify-between mb-8">
                      <h4 className="text-lg font-black text-slate-900 uppercase tracking-widest flex items-center gap-3">
                        <Terminal size={20} className="text-blue-600" /> Formation Engine
                      </h4>
                      {(importFile || reconstructedOutput) && (
                        <div className="flex items-center gap-4">
                           {reconstructedOutput && (
                             <div className="px-4 py-2 bg-blue-50 text-blue-600 rounded-full text-[9px] font-black uppercase border border-blue-100">
                                Output Generated
                             </div>
                           )}
                           {importFile && (
                            <div className="flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-600 rounded-full border border-emerald-100">
                               <FileText size={14} />
                               <span className="text-[10px] font-black uppercase truncate max-w-[150px]">{importFile.name}</span>
                               <button onClick={() => {setImportFile(null); setReconstructedOutput(null);}} className="ml-2 hover:text-rose-500"><X size={14} /></button>
                            </div>
                           )}
                        </div>
                      )}
                   </div>
                   
                   {isGenerating ? (
                     <div className="w-full h-[400px] flex flex-col items-center justify-center text-center">
                        <div className="relative mb-8">
                           <div className="w-20 h-20 border-4 border-blue-50 border-t-blue-600 rounded-full animate-spin" />
                           <div className="absolute inset-0 flex items-center justify-center"><Sparkles size={24} className="text-blue-600 animate-pulse" /></div>
                        </div>
                        <h3 className="text-xl font-black text-slate-900 mb-2">Tehila is deconstructing...</h3>
                        <p className="text-sm text-slate-400 uppercase tracking-widest font-bold">Semantic Mapping in Progress</p>
                     </div>
                   ) : reconstructedOutput ? (
                     <div className="w-full h-[450px] overflow-auto custom-scrollbar animate-in fade-in duration-700">
                        <div className="p-10 bg-slate-950 rounded-[2rem] border border-white/10 shadow-inner font-mono text-[13px] text-emerald-400/90 leading-relaxed">
                           <FormattedResponse text={reconstructedOutput} themeColor="#3b82f6" mode="terminal" />
                        </div>
                        <div className="mt-10 flex items-center justify-center gap-4">
                           <button 
                            onClick={() => setReconstructedOutput(null)}
                            className="px-8 py-4 bg-white border border-slate-200 rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-slate-50 transition-all"
                           >
                              Reset Board
                           </button>
                           <button 
                            onClick={commitToEditor}
                            className="px-10 py-4 bg-blue-600 text-white rounded-2xl font-black text-[10px] uppercase tracking-widest hover:bg-blue-700 shadow-xl shadow-blue-500/20 transition-all flex items-center gap-3 active:scale-95"
                           >
                              Confirm to Studio Editor <ChevronRight size={14} />
                           </button>
                        </div>
                     </div>
                   ) : (
                     <textarea 
                       value={importText}
                       onChange={(e) => setImportText(e.target.value)}
                       disabled={!!importFile}
                       placeholder={importFile ? "Source document is loaded. Intelligence node ready." : "Paste unstructured content here... (Questions, options, and answers in any formation)"}
                       className="w-full h-[400px] bg-transparent outline-none text-lg font-medium leading-relaxed resize-none custom-scrollbar"
                     />
                   )}

                   {!importFile && !reconstructedOutput && !isGenerating && (
                     <div className="mt-8 pt-8 border-t border-slate-50">
                        <input type="file" ref={fileInputRef} onChange={handleImportFileSelect} className="hidden" accept=".pdf" />
                        <button 
                          onClick={() => fileInputRef.current?.click()}
                          className="flex items-center gap-3 px-8 py-4 bg-slate-50 border border-slate-200 rounded-2xl text-slate-600 hover:bg-slate-100 transition-all font-black text-[11px] uppercase tracking-widest"
                        >
                           <Upload size={16} /> Upload Legacy Document
                        </button>
                     </div>
                   )}
                </div>

                <div className="flex items-start gap-6 p-8 bg-blue-50/50 border border-blue-100 rounded-[2.5rem]">
                   <Info size={24} className="text-blue-600 shrink-0 mt-1" />
                   <div>
                      <h5 className="text-sm font-black text-blue-900 uppercase tracking-tight mb-2">Pedagogical Justification</h5>
                      <p className="text-xs text-blue-700 leading-relaxed font-medium">
                        Tehila is configured to reconstruct legacy assets while injecting deep pedagogical explanations. Every correct answer will include a <b>WHY THIS IS CORRECT</b> section for high-retention study sessions.
                      </p>
                   </div>
                </div>
             </div>
          </div>
       </div>

       <aside className="w-[420px] bg-[#fcfdfe] p-12 overflow-y-auto custom-scrollbar flex flex-col shadow-2xl z-20 border-l border-slate-100">
          <div className="mb-12">
             <h3 className="text-3xl font-[1000] text-[#002D56] tracking-tighter mb-4 uppercase">Reconstruct</h3>
             <p className="text-slate-400 text-sm font-medium leading-relaxed">
               Convert legacy formations into high-fidelity structured quiz nodes with automatic justification nodes.
             </p>
          </div>

          <div className="space-y-10">
             <div className="space-y-4">
                <label className="text-sm font-black text-slate-900 uppercase tracking-widest">Formation Logic</label>
                <div className="space-y-2">
                   {[
                     { id: 'mixed', label: 'Mixed Unstructured', icon: <Hash size={14} /> },
                     { id: 'exam', label: 'Legacy Exam Paper', icon: <FileText size={14} /> },
                     { id: 'notes', label: 'Notes-to-Quiz', icon: <AlignLeft size={14} /> }
                   ].map(mode => (
                     <button key={mode.id} className="w-full p-4 bg-white border border-slate-100 rounded-2xl flex items-center justify-between group hover:border-blue-300 transition-all">
                        <div className="flex items-center gap-3">
                           <div className="w-8 h-8 bg-slate-50 rounded-lg flex items-center justify-center text-slate-400 group-hover:text-blue-600 transition-colors">{mode.icon}</div>
                           <span className="text-xs font-black uppercase text-slate-600">{mode.label}</span>
                        </div>
                        {mode.id === 'mixed' && <Check size={14} className="text-blue-600" />}
                     </button>
                   ))}
                </div>
             </div>

             <div className="p-6 bg-[#0f172a] rounded-[2rem] text-white shadow-2xl relative overflow-hidden mt-auto">
                <RefreshCw size={28} className="text-blue-400 mb-4 animate-spin-slow" />
                <h4 className="text-sm font-black uppercase tracking-tight mb-2 leading-none">Intelligence Audit</h4>
                <p className="text-[10px] opacity-60 leading-relaxed font-medium">Reconstruction includes automated justification generation. Tehila will explain the correct path for every question stems.</p>
             </div>
          </div>

          <div className="mt-auto pt-12">
             <button 
               onClick={handleRunImport}
               disabled={isGenerating || (!importText.trim() && !importFile) || !!reconstructedOutput}
               className="w-full py-6 bg-blue-600 hover:bg-blue-700 disabled:opacity-30 text-white rounded-[2rem] font-black text-sm uppercase tracking-[0.25em] transition-all shadow-2xl shadow-blue-500/30 flex items-center justify-center gap-3 active:scale-95"
             >
                {isGenerating ? <Loader2 size={22} className="animate-spin" /> : <Sparkles size={22} />}
                Initiate Reconstruction
             </button>
          </div>
       </aside>
    </div>
  );

  const renderEditor = () => (
    <div className="flex-1 flex overflow-hidden bg-white animate-in slide-in-from-right-4 duration-500">
      {/* Main Workspace (Left) */}
      <div className="flex-1 flex flex-col overflow-y-auto custom-scrollbar border-r border-slate-100">
         <div className="p-12 max-w-4xl mx-auto w-full">
            <nav className="flex items-center gap-2 text-sm font-medium mb-12">
               <button onClick={() => setView('hub')} className="text-blue-600 hover:underline flex items-center gap-1">
                 <ChevronLeft size={16} /> Hub
               </button>
               <span className="text-slate-300">/</span>
               <span className="text-slate-900 font-bold">{quizTitle}</span>
            </nav>

            <div className="relative group mb-20">
               <input 
                 value={quizTitle}
                 onChange={(e) => setQuizTitle(e.target.value)}
                 className="w-full text-6xl font-[1000] tracking-tighter text-[#002D56] outline-none bg-transparent py-4 border-2 border-transparent focus:border-slate-100 rounded-2xl transition-all"
               />
               <Edit3 size={24} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-200 opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity" />
               <div className="h-0.5 w-full bg-slate-50 mt-2" />
            </div>

            {questions.length === 0 ? (
              <div className="flex flex-col items-center py-32 text-center">
                 <h4 className="text-xl font-black text-slate-900 uppercase tracking-widest mb-10">Add Blank Question</h4>
                 <div className="flex flex-wrap justify-center gap-4">
                    <button className="px-8 py-3 bg-blue-50 text-blue-600 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-blue-600 hover:text-white transition-all">Multiple Choice</button>
                    <button className="px-8 py-3 bg-blue-50 text-blue-600 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-blue-600 hover:text-white transition-all">True / False</button>
                    <button className="px-8 py-3 bg-blue-50 text-blue-600 rounded-xl font-black text-xs uppercase tracking-widest hover:bg-blue-600 hover:text-white transition-all">Short Answer</button>
                 </div>
              </div>
            ) : (
              <div className="space-y-12 pb-32">
                 {questions.map((q, idx) => (
                    <div key={q.id} className="bg-slate-50/50 rounded-[2.5rem] p-10 border border-slate-100 animate-in fade-in slide-in-from-bottom-2">
                       <div className="flex items-center justify-between mb-8 opacity-40">
                          <span className="text-[10px] font-black uppercase tracking-widest">Node Output #{idx + 1}</span>
                          <div className="flex items-center gap-2">
                             <button className="p-2 hover:bg-slate-200 rounded-lg"><Edit3 size={14} /></button>
                             <button className="p-2 hover:bg-rose-100 text-rose-500 rounded-lg"><Trash2 size={14} /></button>
                          </div>
                       </div>
                       <div className="prose prose-slate max-w-none">
                          <FormattedResponse text={q.text} themeColor="#135bec" />
                       </div>
                    </div>
                 ))}
                 
                 <div className="pt-10 flex flex-col items-center gap-6">
                    <button className="flex items-center gap-2 px-10 py-4 bg-slate-900 text-white rounded-2xl font-black text-xs uppercase tracking-widest hover:bg-blue-600 transition-all shadow-xl active:scale-95">
                       <Plus size={16} strokeWidth={3} /> Add Manual Question
                    </button>
                    
                    <button 
                      onClick={handleExportToDoc}
                      className="flex items-center gap-3 px-12 py-5 bg-emerald-600 text-white rounded-[2rem] font-black text-sm uppercase tracking-[0.2em] hover:bg-emerald-700 transition-all shadow-2xl shadow-emerald-500/30 active:scale-95 group"
                    >
                       <FileOutput size={20} className="group-hover:translate-y-[-2px] transition-transform" /> 
                       Convert to Classroom Document
                    </button>
                 </div>
              </div>
            )}
         </div>
      </div>

      {/* Intelligence Control (Right) */}
      <aside className="w-[480px] bg-[#fcfdfe] p-12 overflow-y-auto custom-scrollbar flex flex-col shadow-2xl z-20">
         <div className="mb-12">
            <h3 className="text-3xl font-[1000] text-[#002D56] tracking-tighter mb-4 uppercase">Generate Quiz</h3>
            <p className="text-slate-400 text-sm font-medium leading-relaxed">
              Write a detailed prompt describing the questions you wish to generate. Tehila will ensure justifications are included for every correct answer.
            </p>
         </div>

         <div className="space-y-10">
            {/* Prompt Field */}
            <div className="space-y-2">
               <div className="flex justify-between items-center mb-2">
                  <div className="flex items-center gap-2">
                     <label className="text-sm font-black text-slate-900">Prompt</label>
                     <HelpCircle size={16} className="text-blue-500 cursor-help" />
                  </div>
                  <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">{prompt.length} / 3000</span>
               </div>
               <textarea 
                 value={prompt}
                 onChange={(e) => setPrompt(e.target.value)}
                 placeholder="e.g., The solar system and natural satellites. Focus on Jupiter's moons and high-school difficulty level."
                 className="w-full h-40 bg-white border border-slate-200 rounded-xl p-4 text-sm font-medium outline-none focus:ring-4 focus:ring-blue-500/5 focus:border-[#135bec] transition-all shadow-sm"
               />
               <p className="text-[10px] text-slate-400 font-bold italic">Pedagogical explanations are enabled by default. <button className="text-blue-600 underline">Learn More</button></p>
            </div>

            <div className="h-px bg-slate-100" />

            {/* Question Type */}
            <div className="space-y-6">
               <h4 className="text-sm font-black text-slate-900 uppercase tracking-widest">Question Type</h4>
               <div className="space-y-3">
                  {[
                    { id: 'multiple-choice', label: 'Multiple Choice' },
                    { id: 'true-false', label: 'True / False' },
                    { id: 'short-answer', label: 'Short Answer' }
                  ].map(type => (
                    <label key={type.id} className="flex items-center gap-3 cursor-pointer group">
                       <button 
                        type="button"
                        onClick={() => toggleType(type.id)}
                        className={`w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all ${selectedTypes.includes(type.id) ? 'bg-[#135bec] border-[#135bec] text-white shadow-lg' : 'bg-white border-slate-200 group-hover:border-blue-400'}`}
                       >
                          {selectedTypes.includes(type.id) && <Check size={14} strokeWidth={4} />}
                       </button>
                       <span className={`text-sm font-bold ${selectedTypes.includes(type.id) ? 'text-slate-900' : 'text-slate-500'}`}>{type.label}</span>
                    </label>
                  ))}
               </div>
            </div>

            {/* Explanations Toggle */}
            <div className="flex items-center justify-between p-1">
               <div className="flex items-center gap-3">
                  <button 
                    onClick={() => setIncludeExplanations(!includeExplanations)}
                    className={`w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all ${includeExplanations ? 'bg-[#135bec] border-[#135bec] text-white shadow-lg' : 'bg-white border-slate-200'}`}
                  >
                     {includeExplanations && <Check size={14} strokeWidth={4} />}
                  </button>
                  <div className="flex items-center gap-2">
                     <span className={`text-sm font-bold ${includeExplanations ? 'text-slate-900' : 'text-slate-500'}`}>Generate Explanations</span>
                     <HelpCircle size={14} className="text-blue-500" />
                  </div>
               </div>
            </div>

            {/* Question Count */}
            <div className="space-y-4">
               <div className="flex items-center gap-2">
                  <h4 className="text-sm font-black text-slate-900 uppercase tracking-widest">Number of Questions</h4>
                  <HelpCircle size={14} className="text-blue-500" />
               </div>
               <div className="flex items-center gap-2 p-1 bg-slate-50 rounded-xl border border-slate-200 w-fit">
                  {[5, 10, 15].map(count => (
                    <button 
                      key={count}
                      onClick={() => setQuestionCount(count)}
                      className={`px-6 py-2.5 rounded-lg text-xs font-black transition-all ${questionCount === count ? 'bg-[#135bec] text-white shadow-lg' : 'text-slate-400 hover:text-slate-600'}`}
                    >
                      {count}
                    </button>
                  ))}
               </div>
            </div>
         </div>

         <div className="mt-auto pt-10">
            <button 
              onClick={handleGenerate}
              disabled={isGenerating || !prompt.trim()}
              className="w-full py-6 bg-[#135bec] hover:bg-blue-700 disabled:opacity-30 text-white rounded-xl font-black text-sm uppercase tracking-widest transition-all shadow-2xl shadow-blue-600/30 flex items-center justify-center gap-3 active:scale-95"
            >
               {isGenerating ? <Loader2 size={20} className="animate-spin" /> : <Wand2 size={20} />}
               Generate Intelligence
            </button>
         </div>
      </aside>
    </div>
  );

  return (
    <div className="fixed inset-0 z-[120] bg-white flex flex-col animate-in fade-in duration-500 overflow-hidden font-['Inter',_sans-serif]">
      {/* Header */}
      <header className="h-16 bg-white border-b border-slate-100 px-10 flex items-center justify-between shrink-0 z-50">
        <div className="flex items-center gap-6">
          <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-900 transition-all">
            <Home size={24} />
          </button>
          <div className="h-8 w-px bg-slate-100" />
          <div className="flex items-center gap-4">
             <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center text-white shadow-lg">
                <FileSearch size={22} />
             </div>
             <div>
                <h1 className="text-xl font-black text-slate-900 uppercase tracking-tighter">Quiz Intelligence Studio</h1>
                <p className="text-[9px] font-black text-indigo-500 uppercase tracking-[0.3em] mt-0.5">High-Fidelity Lab Node</p>
             </div>
          </div>
        </div>

        <div className="flex items-center gap-4">
           {(view === 'editor' || view === 'importer') && (
             <div className="flex items-center gap-4">
                {view === 'editor' && (
                  <button 
                    onClick={handleExportToDoc}
                    className="flex items-center gap-2 px-6 py-2.5 bg-emerald-50 text-emerald-600 border border-emerald-100 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-100 transition-all"
                  >
                    <FileOutput size={14} /> Export to Doc
                  </button>
                )}
                <button className="flex items-center gap-2 px-8 py-2.5 bg-slate-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-black shadow-xl transition-all active:scale-95">
                  <Save size={14} /> Save to Vault
                </button>
             </div>
           )}
           <button onClick={onClose} className="p-2 text-slate-300 hover:text-rose-500 transition-colors">
             <X size={32} strokeWidth={2.5} />
           </button>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden relative">
        {view === 'hub' ? renderHub() : view === 'importer' ? renderImporter() : renderEditor()}
      </div>
    </div>
  );
};

export default QuizStudio;